// Date: 1/2/2015 10:19:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.hrb1658.petsnailmod.render.entity;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSnail extends ModelBase {
	ModelRenderer body;
	ModelRenderer head;
	ModelRenderer shell;
	ModelRenderer eyeStalkRight;
	ModelRenderer eyeStalkLeft;
	ModelRenderer eyeRight;
	ModelRenderer eyeLeft;

	public ModelSnail() {
		textureWidth = 64;
		textureHeight = 32;

		body = new ModelRenderer(this, 0, 0);
		body.addBox(-2.5F, 0F, -6.5F, 5, 1, 13);
		body.setRotationPoint(0F, 23F, 0F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		head = new ModelRenderer(this, 25, 15);
		head.addBox(-2.5F, 0F, 0F, 5, 1, 3);
		head.setRotationPoint(0F, 22F, -6F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		shell = new ModelRenderer(this, 0, 15);
		shell.addBox(-2.5F, 0F, 0F, 4, 8, 8);
		shell.setRotationPoint(0.5F, 15F, -3F);
		shell.setTextureSize(64, 32);
		shell.mirror = true;
		setRotation(shell, 0F, 0F, 0F);
		eyeStalkRight = new ModelRenderer(this, 37, 0);
		eyeStalkRight.addBox(0F, -6F, 0F, 1, 6, 1);
		eyeStalkRight.setRotationPoint(-1.5F, 22F, -6F);
		eyeStalkRight.setTextureSize(64, 32);
		eyeStalkRight.mirror = true;
		setRotation(eyeStalkRight, 0F, 0F, -0.1745329F);
		eyeStalkLeft = new ModelRenderer(this, 37, 0);
		eyeStalkLeft.addBox(-1F, -6F, 0F, 1, 6, 1);
		eyeStalkLeft.setRotationPoint(1.5F, 22F, -6F);
		eyeStalkLeft.setTextureSize(64, 32);
		eyeStalkLeft.mirror = true;
		setRotation(eyeStalkLeft, 0F, 0F, 0.1745329F);
		eyeRight = new ModelRenderer(this, 42, 0);
		eyeRight.addBox(0F, 0F, 0F, 2, 2, 2);
		eyeRight.setRotationPoint(-3F, 15F, -6.5F);
		eyeRight.setTextureSize(64, 32);
		eyeRight.mirror = true;
		setRotation(eyeRight, 0F, 0F, 0F);
		eyeLeft = new ModelRenderer(this, 50, 0);
		eyeLeft.addBox(0F, 0F, 0F, 2, 2, 2);
		eyeLeft.setRotationPoint(1F, 15F, -6.5F);
		eyeLeft.setTextureSize(64, 32);
		eyeLeft.mirror = true;
		setRotation(eyeLeft, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		body.render(f5);
		head.render(f5);
		shell.render(f5);
		eyeStalkRight.render(f5);
		eyeStalkLeft.render(f5);
		eyeRight.render(f5);
		eyeLeft.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
